name: ray
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-libraries=12.9.1=0
  - cuda-nvrtc=12.9.86=h5888daf_0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.1=0
  - cuda-version=12.9=h4f385c5_3
  - debugpy=1.8.11=py311h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - faiss=1.9.0=py311cuda126h4491dc0_0_cuda
  - faiss-gpu=1.9.0=h418687c_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=9.4.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libblas=3.9.0=34_h59b9bed_openblas
  - libcublas=12.9.1.4=h9ab20c4_0
  - libcufft=11.4.1.4=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=h9ab20c4_0
  - libcusolver=11.7.5.82=0
  - libcusparse=12.5.10.65=0
  - libfaiss=1.9.0=cuda126h4727808_0_cuda
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran=15.1.0=h69a702a_4
  - libgfortran5=15.1.0=hcea5267_4
  - libgomp=15.1.0=h767d61c_4
  - liblapack=3.9.0=34_h7ac8fdf_openblas
  - libnpp=12.4.1.87=0
  - libnvfatbin=12.9.82=0
  - libnvjitlink=12.9.86=0
  - libnvjpeg=12.4.0.76=0
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - ocl-icd=2.3.2=h5eee18b_1
  - openssl=3.5.2=h26f9b46_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - python=3.11.13=h1a3bd86_0
  - python_abi=3.11=2_cp311
  - pyzmq=26.2.0=py311h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py311h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h993c535_1
  - tornado=6.5.1=py311h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==0.33.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiolimiter==1.2.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.10.0
      - anytree==2.13.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.5
      - attrs==25.3.0
      - autograd==1.8.0
      - azure-common==1.1.28
      - azure-core==1.35.0
      - azure-cosmos==4.9.0
      - azure-identity==1.24.0
      - azure-search-documents==11.5.3
      - azure-storage-blob==12.26.0
      - babel==2.17.0
      - beartype==0.18.5
      - beautifulsoup4==4.13.5
      - bitsandbytes==0.43.1
      - bleach==6.2.0
      - blis==1.2.1
      - catalogue==2.0.10
      - certifi==2025.8.3
      - cffi==1.17.1
      - chardet==3.0.4
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpathlib==0.21.1
      - confection==0.1.5
      - conllu==6.0.0
      - contourpy==1.3.3
      - cryptography==45.0.6
      - cycler==0.12.1
      - cymem==2.0.11
      - datasets==4.0.0
      - deep-translator==1.11.4
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - devtools==0.12.2
      - dill==0.3.8
      - distro==1.9.0
      - docstring-parser==0.17.0
      - en-core-web-md==3.8.0
      - en-core-web-sm==3.8.0
      - environs==14.3.0
      - executing==2.2.0
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fnllm==0.4.0
      - fonttools==4.59.1
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - future==1.0.0
      - gensim==4.3.3
      - git-lfs==1.6
      - graphrag==2.5.0
      - graspologic==3.4.1
      - graspologic-native==1.2.5
      - h11==0.16.0
      - h2==3.2.0
      - hf-xet==1.1.5
      - hpack==3.0.0
      - hstspreload==2025.1.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.3
      - hyperframe==5.2.0
      - hyppo==0.4.0
      - idna==2.10
      - ipywidgets==8.1.7
      - isodate==0.7.2
      - isoduration==20.11.0
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.1
      - json-repair==0.49.0
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.7
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - lancedb==0.24.3
      - langcodes==3.5.0
      - language-data==1.3.0
      - lark==1.2.2
      - llvmlite==0.44.0
      - marisa-trie==1.3.0
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - marshmallow==4.0.0
      - matplotlib==3.10.5
      - mdurl==0.1.2
      - mistune==3.1.4
      - mpmath==1.3.0
      - msal==1.33.0
      - msal-extensions==1.3.1
      - multidict==6.6.4
      - multiprocess==0.70.16
      - murmurhash==1.0.13
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - neo4j==5.28.2
      - networkx==3.5
      - nltk==3.9.1
      - nmslib-metabrainz==2.1.3
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.100.1
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.1
      - pandocfilters==1.5.1
      - patsy==1.0.1
      - peft==0.10.0
      - pillow==11.3.0
      - pot==0.9.5
      - preshed==3.0.10
      - prettytable==3.16.0
      - prometheus-client==0.22.1
      - propcache==0.3.2
      - protobuf==6.32.0
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pybind11==3.0.0
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pysbd==0.3.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2025.7.34
      - requests==2.32.4
      - rfc3339-validator==0.1.4
      - rfc3986==1.5.0
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.1.0
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.11.4
      - scispacy==0.5.5
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentence-transformers==5.1.0
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - shtab==1.7.2
      - six==1.17.0
      - smart-open==7.3.0.post1
      - sniffio==1.3.1
      - soupsieve==2.8
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - statsmodels==0.14.5
      - sympy==1.13.1
      - tenacity==9.1.2
      - terminado==0.18.1
      - textblob==0.19.0
      - thinc==8.3.4
      - threadpoolctl==3.6.0
      - tiktoken==0.11.0
      - tinycss2==1.4.0
      - tokenizers==0.19.1
      - torch==2.3.1+cu121
      - torch-geometric==2.6.1
      - torchaudio==2.3.1+cu121
      - torchvision==0.18.1+cu121
      - tqdm==4.67.1
      - transformers==4.44.2
      - triton==2.3.1
      - trl==0.11.4
      - typeguard==4.4.4
      - typer==0.16.0
      - types-python-dateutil==2.9.0.20250822
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tyro==0.9.31
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wasabi==1.1.3
      - weasel==0.4.1
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.14
      - wrapt==1.17.3
      - xgboost==3.0.4
      - xxhash==3.5.0
      - yarl==1.20.1
prefix: /home/st426/miniconda3/envs/ray
